[package]
name = "tkhq_client"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
doctest = false

[dependencies]
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
tkhq_api_key_stamper = { path = "../api_key_stamper" }
prost = { version = "0.12" }
prost-types = { version = "0.12" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
thiserror = { version = "2.0.12" }
tokio = { version = "1.44.2" }

[dev-dependencies]
wiremock = "0.6"
http = "0.2"
