[package]
name = "tkhq_client"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
tkhq_api_key_stamper = { path = "../api_key_stamper" }
prost = { version = "0.12" }
prost-types = { version = "0.12" }
