[package]
name = "tkhq_examples"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
description = "Examples using the Turnkey Rust SDK"
publish = false

[dependencies]
tkhq_api_key_stamper = { path = "../api_key_stamper" }
tkhq_enclave_encrypt = { path = "../enclave_encrypt" }
tkhq_client = { path = "../client" }
dotenvy = { version = "0.15.0" }
hex = { version = "0.4.3", default-features = false, features = ["std"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.44.1", features = ["full"] }
serde_json = { version = "1.0.140" }
